### ISSUE TITLE
backward conversion

### ISSUE THREAD

**Issue by KSX5** [Jeefongithub/FreeTubeHistoryToYouTubeWatchmarker#1]
Dear @Jeefongithub

first of all, this is not an issue it's more an idea/request (and i don't know another way to contact a user on GitHub)

would it be possible, or do u have a script to convert the data backwards?
**YouTubeWatchmarker to FreeTube**

I'm currently trying to migrate my YouTube history to FreeTube and I only have my browser chronic and the Youtube Watchmaker history data.
I have seen your request on the Youtube Watchmake GitHub (Feature Request: Export history for FreeTube import #112) for this and sniklaus shared a python script to convert the data into .JSON

I tried that out, but it didn't work

I also tried to convert the .JSON file with FreeTube-Legacy-Converter, but it was also not possible for FreeTube to read the data.

Maybe u can help me out here? Thanks in advance. Cheers!

**Comment by Jeefongithub** [comment]
@KSX5 I tried for a while to make something to go in reverse but the roadblock I think I ran into was FreeTube requires more datapoints then the export from Youtube Watchmarker exports. This was a while ago so i can't remember which of those i would get caught up on. If you want to try it best of luck but at this time I'm sticking with FreeTube and I'll just be missing a few of my watch histories
